# ReplicaSet definition
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: wisecow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: my-container-1
        image: rahhulbusiness415/wisecow-app:latest
        ports:
        - containerPort: 32586
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: my-container-2
        image: rahhulbusiness415/wisecow-app:latest
        ports:
        - containerPort: 32586
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      nodeSelector:
        role: worker
      tolerations:
      - key: "key"
        operator: "Equal"
        value: "value"
        effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app"
                operator: "In"
                values:
                - "wisecow"
            topologyKey: "kubernetes.io/hostname"
---
# Service definition
apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 32586
      nodePort: 32586
  type: NodePort

