apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80        # Port on which the service will be exposed
      targetPort: 32586 # Port on the container
      nodePort: 32586   # NodePort to expose on the node
  type: NodePort

